<?php
declare(strict_types=1);

/**
 * Uuid  --  UUIDv4 as 16 raw bytes, generated by the application (build spec
 * section 19). The application supplies binary ids; it does not rely on
 * database-generated ids. Storage matches UUID_TO_BIN semantics (raw bytes).
 */
final class Uuid
{
    /** Generate a random UUIDv4 as 16 raw bytes. */
    public static function bin(): string
    {
        $bytes = random_bytes(16);
        $bytes[6] = chr((ord($bytes[6]) & 0x0F) | 0x40); // version 4
        $bytes[8] = chr((ord($bytes[8]) & 0x3F) | 0x80); // variant 10
        return $bytes;
    }

    /** 16 raw bytes -> canonical 8-4-4-4-12 lowercase hyphenated string. */
    public static function toString(string $bin): string
    {
        if (strlen($bin) !== 16) {
            throw new InvalidArgumentException('Uuid::toString expects 16 bytes.');
        }
        $hex = bin2hex($bin);
        return substr($hex, 0, 8) . '-' . substr($hex, 8, 4) . '-'
            . substr($hex, 12, 4) . '-' . substr($hex, 16, 4) . '-'
            . substr($hex, 20, 12);
    }

    /** Hyphenated (or bare 32-hex) string -> 16 raw bytes. */
    public static function fromString(string $uuid): string
    {
        $hex = strtolower(str_replace('-', '', $uuid));
        if (strlen($hex) !== 32 || !ctype_xdigit($hex)) {
            throw new InvalidArgumentException('Uuid::fromString invalid uuid.');
        }
        return hex2bin($hex);
    }
}
